version: "3.8"
services:
  db:
    image: postgres
    container_name: short-notes-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: short-notes-db
    ports:
      - "5433:5432"